# -*- coding: utf-8 -*-
"""Colab'e hoş geldiniz.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# **Starbucks drinks calories analysis**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('starbucks-menu-nutrition-drinks.csv')
df.head(5)

df.columns

df.info()

df.describe()

df.isnull().sum()

df=df.rename(columns={"Unnamed: 0" : "drink_name"})

df=df.replace({"-":None})
df.head(4)

df=df.dropna()

for col in df.columns[1:]:
        df[col] = pd.to_numeric(df[col])

cal=df.sort_values("Calories", ascending=True)
cal

sns.histplot(df["Calories"], bins=30, kde=True)
plt.title("Calories")
plt.xlabel("Calorie")
plt.ylabel("Drink Count")
plt.show()

healthy_df = df[
    (df["Calories"] < 150) &
    (df["Carb. (g)"] < 20) &
    (df["Protein"] > 0)
    ]

# En sağlıklı içecekleri görelim
healthy_df[["drink_name", "Calories", "Carb. (g)", "Protein"]].sort_values("Calories")

plt.figure(figsize=(12,6))
sns.barplot(
    data=healthy_df.sort_values("Calories"),
    x="Calories", y="drink_name",
    hue="drink_name",
    palette="Greens_r",
    legend=False
)
plt.title("Healthy Drinks by Calories")
plt.xlabel("Calorie")
plt.ylabel("Drink Name")
plt.show()